# Generated by Django 5.2.5 on 2025-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_link_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Код привязки Telegram",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_link_code_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Срок действия кода привязки"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="Имя пользователя в Telegram (без @)",
                max_length=100,
                null=True,
                verbose_name="Telegram Username",
            ),
        ),
    ]
